<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.2.1</Version>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Igor Tyulyakov aka g101k</Authors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>EFCore application settings provider</Title>
        <PackageProjectUrl>https://github.com/g10101k/Oip.Settings</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/g10101k/Oip.Settings</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Oip.Settings.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <None Include=".\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.22"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.22"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0"/>
    </ItemGroup>

</Project>
