<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.3.1</Version>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Igor Tyulyakov aka g101k</Authors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>EFCore application settings provider</Title>
        <PackageProjectUrl>https://github.com/g10101k/Oip.Settings</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/g10101k/Oip.Settings</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>./icon.png</PackageIcon>
    </PropertyGroup>
    <ItemGroup Label="Files">
        <None Include="./icon.png" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Oip.Settings.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.36"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.36"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.36"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.29"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="6.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.2"/>
        <PackageReference Include="Mcrio.Configuration.Provider.Docker.Secrets" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.22"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1"/>
        <PackageReference Include="Mcrio.Configuration.Provider.Docker.Secrets" Version="1.0.1" />
    </ItemGroup>

</Project>
